### ISSUE TITLE
Kanban Review

### ISSUE THREAD

**Issue by AkshithaReddy1899** [AkshithaReddy1899/React-group-project#25]
Hello, We are a team of two people including @brytebee  and @AkshithaReddy1899.

Here's a [link](https://github.com/AkshithaReddy1899/React-group-project/projects/2) for our project.

**Comment by dasileker** [comment]
### **Hi @AkshithaReddy1899 ,** 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AkshithaReddy1899** [comment]
Thank you
